### ISSUE TITLE
Model unresponsive

### ISSUE THREAD

**Issue by mashastroganova** [Azure-Samples/aisearch-openai-rag-audio#25]
Hi, 

With the latest version, I repeatedly get this error when starting the conversation : 

`
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/app/backend/rtmt.py", line 208, in _websocket_handler
    await self._forward_messages(ws)
  File "/workspaces/aisearch-openai-rag-audio/app/backend/rtmt.py", line 180, in _forward_messages
    async with session.ws_connect("/openai/realtime", headers=headers, params=params) as target_ws:
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 832, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 545, in _request
    req = self._request_class(
          ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 303, in __init__
    url2 = url.with_query(params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/yarl/_url.py", line 1400, in with_query
    new_query = self._get_str_query(*args, **kwargs) or ""
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/yarl/_url.py", line 1360, in _get_str_query
    return cls._get_str_query_from_sequence_iterable(query.items())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/yarl/_url.py", line 1288, in _get_str_query_from_sequence_iterable
    f"{quoter(k)}={quoter(v if type(v) is str else cls._query_var(v))}"
                                                   ^^^^^^^^^^^^^^^^^
  File "/workspaces/aisearch-openai-rag-audio/.venv/lib/python3.12/site-packages/yarl/_url.py", line 1317, in _query_var
    raise TypeError(
TypeError: Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>
`

At the same time, I can see that the websocket connection is being opened and closed constantly:
![image](https://github.com/user-attachments/assets/c5563b7e-98d5-4713-b960-82a84441bcea)

Model is completely unresponsive. With the previous version (maybe around 2 weeks ago?) it worked just fine :)

**Comment by jakeatmsft** [comment]
@mashastroganova  - can you comment on why you closed this?  I am getting the same issues

**Comment by pamelafox** [comment]
Can you print out the headers and parameters that are being sent from rtmt.py (the line that causes the traceback)? Just want to make sure that it's being configured properly, there's been some environment variable changes.
